# Results  

```{r, include=FALSE}

library(dataRetrieval)
library(tidyverse)
library(trend)
library(lubridate)
knitr::opts_chunk$set(echo = TRUE)

```

## Data Acquisition 

```{r}
##Surface water discharge data

site_ca <- "10265150" 
q_ca <- readNWISdv(siteNumbers = site_ca, 
                parameterCd = '00060', 
                startDate = '1992-01-19', 
                endDate = '2022-04-06') %>% 
  rename(q_cfs = X_00060_00003) %>%
  addWaterYear(.) %>%
  select(-agency_cd, -X_00060_00003_cd) %>%
  mutate(Site = "Hot CA Flume SW") %>%
  select(-site_no)


```


```{r}
##Ground water data

gw_depth <- read_csv('gw_data.csv')

gw_depth <- gw_depth %>%
  mutate(Site = "Hot Creek GW") %>%
  select(-site)

```

```{r}
##Climate Data

mam_climate <- read_csv('Date_Mammoth_climate.csv')

```

## Attribute Analysis

Groundwater Depth 

```{r}
ggplot(gw_depth, aes(x = Date, y = water_depth)) + 
  geom_line() + 
  ylab('Ground Water Depth (feet)') +
  theme_bw()
```

Surface Water Discharge

```{r}
ggplot(q_ca, aes(x = Date, y = q_cfs)) + 
  geom_line() + 
  ylab('Q (cfs)') +
  theme_bw()
```

GW and SW Long

```{r}

sw_gw <- left_join(gw_depth, q_ca, by = "Date")

sw_gw_graph <- ggplot() +
    geom_line(data = sw_gw, aes(x=Date, y=water_depth*3), color = 'grey') +  
    geom_line(data = sw_gw, aes(x=Date, y=q_cfs), color = 'lightblue') 

   
sw_gw_graph + scale_y_continuous(sec.axis = sec_axis(~./3)) + 
  theme_bw() + 
  ylab("GW Depth(F)") +
  xlab("Date")
```

Temperature and Precipitation 

```{r}

t_annual <- mam_climate %>%
  dplyr::mutate(month = month(Date),
                year = year(Date)) %>%
  group_by(year) %>%
  summarize(Avrg_T = mean(Avrg_T, na.rm = T)) 

p_annual <- mam_climate %>%
  dplyr::mutate(month = month(Date),
                year = year(Date)) %>%
  group_by(year) %>%
  summarize(Precip = mean(Precip, na.rm = T))

t_p_annual <- cbind(t_annual, p_annual) %>%
  select(-3)

ggplot(t_p_annual, aes(x=Avrg_T, y=Precip)) +
  geom_point()

t_p <- ggplot() +
  geom_line(data = mam_climate, aes(x=Date, y= Avrg_T), color = 'red') +
  geom_line(data = mam_climate, aes(x=Date, y=Precip), color = 'blue') 

t_p + scale_y_continuous(sec.axis = sec_axis(~./1)) +
  theme_bw() + 
  ylab("Temp(F)") +
  xlab("Date")
```

Monthly Water Trends

```{r}

q_month_means <- q_ca %>%
  dplyr::mutate(month = month(Date),
                year = year(Date)) %>%
  group_by(year, month) %>%
  summarize(q_mean = mean(q_cfs, na.rm = T))

head(q_month_means) 

```

Discharge Trends for baseflow months

```{r}

q_base <- q_month_means %>% 
  filter(month %in% c('7','8','9','10'))

ggplot(q_base, aes( x= year, y= q_mean)) +
  geom_point(aes(color = factor(month))) + 
  scale_y_log10() +
  ylab('Q (cfs)') +
  xlab('Water Year')+
  scale_color_brewer()

```

## Statistical Trend Analysis

```{r}
#Surface Water Discharge 

mk.test(log10(q_month_means$q_mean))

sens.slope(q_month_means$q_mean)

#Baseflow month trends

mk.test(log10(q_base$q_mean))

sens.slope(q_base$q_mean)

```

```{r}
#Ground Water Level

mk.test(log10(gw_depth$water_depth))

sens.slope(gw_depth$water_depth)
```



## Annual Temperature 

