---
title: "discussion"
author: "Sierra Klemme"
date: "5/2/2022"
output: html_document
---


# Discussion

  With an ever-changing climate, water becomes quite a big deal in a lot of conversations. Previous work by
Justin hintington supports the claim that all components
of the water budget are in some way affected by temperature and precipitation.[@huntington_role_2012] 
The goal of this report was to further prove this 
statement, showing how changing climate variables 
such as temperature and precipitation cause a noticeable effect on groundwater levels
and its relation to surface water baseflow 
discharge rates. 
   
   Using the Hot Creek site near Mammoths Lake, 
California all four variables were able to be 
measured and compared objectively. From this 
report figures 4.1 and 4.2 showed the trends
of groundwater and surface water discharge from 
1992 to 2022. From these graphs, there are evident 
positive trends in the groundwater data showing 
that over time the water table is getting deeper. 
This trend was proven by the Sen's Slope test 
where groundwater was found to have a slope of
0.0003. When referring to groundwater a positive value translates to a 
deepening of the water table. While this slope is gradual it is in fact
seen to be very significant for groundwater. 
For only a 30 year time period groundwater in the
Mammoth Lakes area dropped by 4.43 feet, if this 
trend was to continue it could be detrimental 
to the groundwater supply. The surface water discharge
did not have the same obvious effects of a declining 
trend but overall there is a decrease in discharge rates
of 0.03 cubic feet per year. With this general 
understanding of the types of trends for water supply
along Hot Creek, the climate variables were then
analyzed to correlate their effects.

   Temperature and precipitation were also analyzed
for their trends before being compared
for their effects on the water sources. Figure 4.4
shows the patterns of temperature and precipitation
from 1992 to 2017. From this visual, it is interpreted
that temperature and precipitation correlate
in the way that when temperature increases, 
precipitation decreases, and the opposite is true. From this,
we can further correlate how these attributes
affect water through evaporation and groundwater
recharge potentials. After this initial analysis of
the individual components, their relationships were 
then quantified. 

   How groundwater is affected by precipitation and
temperature was the main relationship in consideration
for this analysis. Figure 4.5 shows groundwater 
compared to temperature and precipitation. 
By comparing groundwater to the climate 
characteristics, further analysis on what types of trends can be predicted 
in times of climate change. Temperature showed to have a 
more significant relationship with groundwater depths. Having proven that 
temperature affects precipitation it is given that temperature has a 
stronger pull on water supply. Temperature affects water through 
evaporation, recharge possibilities, and water needs for population use. 

   The final comparison was to explore how these factors affect baseflow
discharge knowing the strongest influences from groundwater on surface 
water discharge is during baseflow [@kalbus_measuring_2006]. Figure 4.6 shows discharge 
for baseflow months with a variation of years where the months have little range
and other years where there are major differences in July and October. When comparing
these trends to baseflow months of groundwater depths, figure 4.7, it becomes
apparent that there is not much overlap but when looking at the end of the study
time, possible correlations are seen in October. Figure 4.8 shows groundwater
depth and discharge for October and a noticeable trend is seen in how
discharge decreases with an increasing water table depth, especially as time goes
on. The lighter points representing later years show a significant increasing trend
that water depths are getting deeper and discharge is decreasing. These results 
indicate significant changes in groundwater and surface water discharge. 

# Conclusion 

   When looking back to the temperature and precipitation graphs there is more
variation in patterns within the past 10 years. From this understanding, it is
reasonable to correlate the steadily decreasing measurements of discharge and 
groundwater depth is caused by the influences of changing climate patterns. This
location allowed for these conclusions to be deciphered but research at a larger
scale with more evidence that the groundwater from the upstream site was truly
resurfacing at the surface water site would strengthen these findings. It is 
with certainty that climate patterns in the Mammoth Lakes area are positively 
trending and that there is more to be said about its direct influence on baseflow 
patterns. In the end, this report supports the need to collect greater amounts of evidence
on groundwater and how it deserves more attention for future cases to show its pertinence in the global water supply. Learning how to manage and conserve
both groundwater and surface water sources will benefit generations to come and 
help guarantee a better understanding of the water budget to predict future 
trends.
