#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2020.nc 
